/**
 * CAR rental service
 * This is a Car rental Webservice to rent cars. For further information, please visit our [Wiki] (https://se-2022.atlassian.net/wiki/)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Car { 
    id?: string;
    chassis_number?: string;
    manufacturer?: string;
    construction_year?: string;
    color?: string;
    model?: string;
    model_series?: string;
    engine_fuel?: string;
    engine_fuel_consumption?: number;
    engine_performance?: number;
    engine_type?: string;
    gear_type?: string;
    adblue?: boolean;
    seats?: number;
    price_in_euro_cent?: number;
}

