/**
 * Car Rental Webservice
 * This is backend web service for the Car Rental application. For further information, please visit our [Wiki](https://se-2022.atlassian.net/wiki/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Currency { 
    symbol?: Currency.SymbolEnum;
    rate?: number;
}
export namespace Currency {
    export type SymbolEnum = 'USD' | 'JPY' | 'BGN' | 'CZK' | 'DKK' | 'GBP' | 'HUF' | 'PLN' | 'RON' | 'SEK' | 'CHF' | 'ISK' | 'NOK' | 'HRK' | 'TRY' | 'AUD' | 'BRL' | 'CAD' | 'CNY' | 'HKD' | 'IDR' | 'ILS' | 'INR' | 'KRW' | 'MXN' | 'MYR' | 'NZD' | 'PHP' | 'SGD' | 'THB' | 'ZAR' | 'EUR';
    export const SymbolEnum = {
        Usd: 'USD' as SymbolEnum,
        Jpy: 'JPY' as SymbolEnum,
        Bgn: 'BGN' as SymbolEnum,
        Czk: 'CZK' as SymbolEnum,
        Dkk: 'DKK' as SymbolEnum,
        Gbp: 'GBP' as SymbolEnum,
        Huf: 'HUF' as SymbolEnum,
        Pln: 'PLN' as SymbolEnum,
        Ron: 'RON' as SymbolEnum,
        Sek: 'SEK' as SymbolEnum,
        Chf: 'CHF' as SymbolEnum,
        Isk: 'ISK' as SymbolEnum,
        Nok: 'NOK' as SymbolEnum,
        Hrk: 'HRK' as SymbolEnum,
        Try: 'TRY' as SymbolEnum,
        Aud: 'AUD' as SymbolEnum,
        Brl: 'BRL' as SymbolEnum,
        Cad: 'CAD' as SymbolEnum,
        Cny: 'CNY' as SymbolEnum,
        Hkd: 'HKD' as SymbolEnum,
        Idr: 'IDR' as SymbolEnum,
        Ils: 'ILS' as SymbolEnum,
        Inr: 'INR' as SymbolEnum,
        Krw: 'KRW' as SymbolEnum,
        Mxn: 'MXN' as SymbolEnum,
        Myr: 'MYR' as SymbolEnum,
        Nzd: 'NZD' as SymbolEnum,
        Php: 'PHP' as SymbolEnum,
        Sgd: 'SGD' as SymbolEnum,
        Thb: 'THB' as SymbolEnum,
        Zar: 'ZAR' as SymbolEnum,
        Eur: 'EUR' as SymbolEnum
    };
}


