/**
 * Car Rental Webservice
 * This is backend web service for the Car Rental application. For further information, please visit our [Wiki](https://se-2022.atlassian.net/wiki/)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Car } from './car';
import { Location } from './location';


export interface Order {
    orderId: BigInt;
    car: Car;
    location_of_rental: Location;
    location_of_return: Location;
    date_of_booking: string;
    date_of_rental: string;
    date_of_return: string;
    method_of_payment: Order.MethodOfPaymentEnum;
    card_number: string;
    card_security_code: string;
    valid_until: string;
    first_name: string;
    last_name: string;
    email: string;
    order_status: Order.OrderStatusEnum;
    saga_status: Order.SagaStatusEnum
}
export namespace Order {
    export type MethodOfPaymentEnum = 'DINERS_CLUB' | 'VISA' | 'MASTERCARD' | 'AMERICAN_EXPRESS';
    export const MethodOfPaymentEnum = {
        DinersClub: 'DINERS_CLUB' as MethodOfPaymentEnum,
        Visa: 'VISA' as MethodOfPaymentEnum,
        Mastercard: 'MASTERCARD' as MethodOfPaymentEnum,
        AmericanExpress: 'AMERICAN_EXPRESS' as MethodOfPaymentEnum
    };
    export type OrderStatusEnum = 'CREATED' | 'CANCELED' | 'ACTIVE' | 'RETURNED';
    export const OrderStatusEnum = {
        Created: 'CREATED' as OrderStatusEnum,
        Canceled: 'CANCELED' as OrderStatusEnum,
        Active: 'ACTIVE' as OrderStatusEnum,
        Returned: 'RETURNED' as OrderStatusEnum
    };

  export type SagaStatusEnum = 'CREATED' | 'FINISHED' | 'CAR_REJECTED' | 'LOCATION_REJECTED';
  export const SagaStatusEnum = {
    Created: 'CREATED' as SagaStatusEnum,
    Finished: 'FINISHED' as SagaStatusEnum,
    CarRejected: 'CAR_REJECTED' as SagaStatusEnum,
    LocationRejected: 'LOCATION_REJECTED' as SagaStatusEnum,
  };
}


