/**
 * CAR rental service
 * This is a Car rental Webservice to rent cars. For further information, please visit our [Wiki] (https://se-2022.atlassian.net/wiki/)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Order { 
    id?: string;
    order_date?: string;
    date_from?: string;
    date_to?: string;
    discount?: number;
    purchase_option?: string;
}

