/**
 * Car Rental Webservice
 * This is backend web service for the Car Rental application. For further information, please visit our [Wiki](https://se-2022.atlassian.net/wiki/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Updated location object
 */
export interface UpdateLocationRequest { 
    location_name: string;
    street_name: string;
    street_number: string;
    city_name: string;
    postal_code: number;
    email: string;
    phone: string;
    latitude: string;
    longitude: string;
}

