export * from './auth.service';
import { AuthService } from './auth.service';
export * from './car.service';
import { CarService } from './car.service';
export * from './currency.service';
import { CurrencyService } from './currency.service';
export * from './location.service';
import { LocationService } from './location.service';
export * from './openingHours.service';
import { OpeningHoursService } from './openingHours.service';
export * from './order.service';
import { OrderService } from './order.service';
export const APIS = [AuthService, CarService, CurrencyService, LocationService, OpeningHoursService, OrderService];
