/**
 * CAR rental service
 * This is a Car rental Webservice to rent cars. For further information, please visit our [Wiki] (https://se-2022.atlassian.net/wiki/)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Car { 
    id?: string;
    chassisNumber?: string;
    manufacturer?: string;
    constructionYear?: string;
    color?: string;
    model?: string;
    modelSeries?: string;
    engineFuel?: string;
    engineFuelConsumption?: number;
    enginePerformance?: number;
    engineType?: string;
    gearType?: string;
    adblue?: boolean;
    seats?: number;
    priceInEuroCent?: number;
}