/**
 * CAR rental service
 * This is a Car rental Webservice to rent cars. For further information, please visit our [Wiki] (https://se-2022.atlassian.net/wiki/)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Response { 
    /**
     * The success code, 0 or -1.
     */
    code: number;
    /**
     * The description message for this success code
     */
    message: string;
    /**
     * A map of errors within the request. Keyed by the parameter name and the values are the error details
     */
    errors?: Array<Error>;
}